### ISSUE TITLE
Réflexion funny action

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/eurobot#62]
_From @mistic100 on November 11, 2016 13:15_

La NASA vient de publier un paquet de modèles 3D https://github.com/nasa/NASA-3D-Resources
Peut être qu'il y en a qu'on peut imprimer

_Copied from original issue: ARIG-Robotique/robots#28_

**Comment by gdepuille** [comment]
@ARIG-Robotique/eurobot : Mais c'est bon ça. J'aime beaucoup le module lunaire.

**Comment by gdepuille** [comment]
Finalement une hélice.
